# Generated by Django 3.0.2 on 2020-03-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
