# Generated by Django 3.0.2 on 2020-03-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lable',
            field=models.CharField(choices=[('new', 'new'), ('best_saler', 'best_saler')], max_length=50),
        ),
    ]
